/** \file
*   \brief ThingRendevous's Task Info implementation 
*
* Generated by Trtgen.py.
*/
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "trBidt.h"
#include "trPl.h"
#include "trEvt.h"
#include "trMsg.h"
#include "trStrm.h"
#include "trT.h"
#include "trEvtP.h"
#include "trMsgP.h"
#include "trStrmP.h"
#include "trTP.h"
#include "trTi.h"
/* No need for trTi_Strm_DB_Tst01AAAA_43690_3. */
/* No need for trTi_Strm_CB_Tst01AAAA_43690_3. */
/* No need for trTi_Strm_CI_Tst01AAAA_43690_3. */
/* No need for trTi_Msg_PL_Tst01AAAA_43690_3. */
/* No need for trTi_Msg_PY_Tst01AAAA_43690_3. */
/* No need for trTi_Msg_DB_Tst01AAAA_43690_3. */
/* No need for trTi_Msg_CB_Tst01AAAA_43690_3. */
/* No need for trTi_Msg_CI_Tst01AAAA_43690_3. */
/* No need for trTi_Evt_PL_Tst01AAAA_43690_3. */
/* No need for trTi_Evt_DB_Tst01AAAA_43690_3. */
/* No need for trTi_Evt_CB_Tst01AAAA_43690_3. */
/* No need for trTi_Evt_CI_Tst01AAAA_43690_3. */
uint64_t trTi_Task_SB_Tst01AAAA_43690_3[128]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_Tst01AAAA_43690_3;
void trTask_Tst01AAAA(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_Tst01AAAA_43690_3 =
{
	&trTi_Task_CB_Tst01AAAA_43690_3, /* ci_cb_p */ 
	trTask_Tst01AAAA, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_Tst01AAAA_43690_3[0], /* ci_sb_p */ 
	1024, /* ci_StackSize */ 
	32767 /* ci_NominalPriority */ 
};
/* No need for trTi_Strm_DB_trTst01_init_255_5. */
/* No need for trTi_Strm_CB_trTst01_init_255_5. */
/* No need for trTi_Strm_CI_trTst01_init_255_5. */
/* No need for trTi_Msg_PL_trTst01_init_255_5. */
/* No need for trTi_Msg_PY_trTst01_init_255_5. */
/* No need for trTi_Msg_DB_trTst01_init_255_5. */
/* No need for trTi_Msg_CB_trTst01_init_255_5. */
/* No need for trTi_Msg_CI_trTst01_init_255_5. */
/* No need for trTi_Evt_PL_trTst01_init_255_5. */
/* No need for trTi_Evt_DB_trTst01_init_255_5. */
/* No need for trTi_Evt_CB_trTst01_init_255_5. */
/* No need for trTi_Evt_CI_trTst01_init_255_5. */
uint64_t trTi_Task_SB_trTst01_init_255_5[128]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_trTst01_init_255_5;
void trTask_trTst01_init(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_trTst01_init_255_5 =
{
	&trTi_Task_CB_trTst01_init_255_5, /* ci_cb_p */ 
	trTask_trTst01_init, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_trTst01_init_255_5[0], /* ci_sb_p */ 
	1024, /* ci_StackSize */ 
	255 /* ci_NominalPriority */ 
};
uint8_t trTi_Strm_DB_Tst01BBBB_48059_6[24];
struct trStrmP_CB_s trTi_Strm_CB_Tst01BBBB_48059_6;
const struct trStrmP_CI_s trTi_Strm_CI_Tst01BBBB_48059_6 =
{
	24, /* ci_StrmLen */ 
	&trTi_Strm_CB_Tst01BBBB_48059_6, /* ci_cb_p */ 
	&trTi_Strm_DB_Tst01BBBB_48059_6[0]  /* ci_db_p */ 
};
/* No need for trTi_Msg_PL_Tst01BBBB_48059_6. */
/* No need for trTi_Msg_PY_Tst01BBBB_48059_6. */
/* No need for trTi_Msg_DB_Tst01BBBB_48059_6. */
/* No need for trTi_Msg_CB_Tst01BBBB_48059_6. */
/* No need for trTi_Msg_CI_Tst01BBBB_48059_6. */
/* No need for trTi_Evt_PL_Tst01BBBB_48059_6. */
/* No need for trTi_Evt_DB_Tst01BBBB_48059_6. */
/* No need for trTi_Evt_CB_Tst01BBBB_48059_6. */
/* No need for trTi_Evt_CI_Tst01BBBB_48059_6. */
uint64_t trTi_Task_SB_Tst01BBBB_48059_6[128]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_Tst01BBBB_48059_6;
void trTask_Tst01BBBB(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_Tst01BBBB_48059_6 =
{
	&trTi_Task_CB_Tst01BBBB_48059_6, /* ci_cb_p */ 
	trTask_Tst01BBBB, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_Tst01BBBB_48059_6[0], /* ci_sb_p */ 
	1024, /* ci_StackSize */ 
	32767 /* ci_NominalPriority */ 
};
/* No need for trTi_Strm_DB_Tei_64_0. */
/* No need for trTi_Strm_CB_Tei_64_0. */
/* No need for trTi_Strm_CI_Tei_64_0. */
/* No need for trTi_Msg_PL_Tei_64_0. */
/* No need for trTi_Msg_PY_Tei_64_0. */
/* No need for trTi_Msg_DB_Tei_64_0. */
/* No need for trTi_Msg_CB_Tei_64_0. */
/* No need for trTi_Msg_CI_Tei_64_0. */
/* No need for trTi_Evt_PL_Tei_64_0. */
/* No need for trTi_Evt_DB_Tei_64_0. */
/* No need for trTi_Evt_CB_Tei_64_0. */
/* No need for trTi_Evt_CI_Tei_64_0. */
uint64_t trTi_Task_SB_Tei_64_0[1]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_Tei_64_0;
void trTask_Tei(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_Tei_64_0 =
{
	&trTi_Task_CB_Tei_64_0, /* ci_cb_p */ 
	trTask_Tei, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_Tei_64_0[0], /* ci_sb_p */ 
	8, /* ci_StackSize */ 
	64 /* ci_NominalPriority */ 
};
/* No need for trTi_Strm_DB_trTst01_action_256_2. */
/* No need for trTi_Strm_CB_trTst01_action_256_2. */
/* No need for trTi_Strm_CI_trTst01_action_256_2. */
/* No need for trTi_Msg_PL_trTst01_action_256_2. */
/* No need for trTi_Msg_PY_trTst01_action_256_2. */
/* No need for trTi_Msg_DB_trTst01_action_256_2. */
/* No need for trTi_Msg_CB_trTst01_action_256_2. */
/* No need for trTi_Msg_CI_trTst01_action_256_2. */
/* No need for trTi_Evt_PL_trTst01_action_256_2. */
/* No need for trTi_Evt_DB_trTst01_action_256_2. */
/* No need for trTi_Evt_CB_trTst01_action_256_2. */
/* No need for trTi_Evt_CI_trTst01_action_256_2. */
uint64_t trTi_Task_SB_trTst01_action_256_2[128]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_trTst01_action_256_2;
void trTask_trTst01_action(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_trTst01_action_256_2 =
{
	&trTi_Task_CB_trTst01_action_256_2, /* ci_cb_p */ 
	trTask_trTst01_action, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_trTst01_action_256_2[0], /* ci_sb_p */ 
	1024, /* ci_StackSize */ 
	32767 /* ci_NominalPriority */ 
};
/* No need for trTi_Strm_DB_Tst01CCCC_52428_4. */
/* No need for trTi_Strm_CB_Tst01CCCC_52428_4. */
/* No need for trTi_Strm_CI_Tst01CCCC_52428_4. */
/* No need for trTi_Msg_PL_Tst01CCCC_52428_4. */
/* No need for trTi_Msg_PY_Tst01CCCC_52428_4. */
/* No need for trTi_Msg_DB_Tst01CCCC_52428_4. */
/* No need for trTi_Msg_CB_Tst01CCCC_52428_4. */
/* No need for trTi_Msg_CI_Tst01CCCC_52428_4. */
/* No need for trTi_Evt_PL_Tst01CCCC_52428_4. */
/* No need for trTi_Evt_DB_Tst01CCCC_52428_4. */
/* No need for trTi_Evt_CB_Tst01CCCC_52428_4. */
/* No need for trTi_Evt_CI_Tst01CCCC_52428_4. */
uint64_t trTi_Task_SB_Tst01CCCC_52428_4[128]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_Tst01CCCC_52428_4;
void trTask_Tst01CCCC(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_Tst01CCCC_52428_4 =
{
	&trTi_Task_CB_Tst01CCCC_52428_4, /* ci_cb_p */ 
	trTask_Tst01CCCC, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_Tst01CCCC_52428_4[0], /* ci_sb_p */ 
	1024, /* ci_StackSize */ 
	32767 /* ci_NominalPriority */ 
};
/* No need for trTi_Strm_DB_Tti_128_1. */
/* No need for trTi_Strm_CB_Tti_128_1. */
/* No need for trTi_Strm_CI_Tti_128_1. */
/* No need for trTi_Msg_PL_Tti_128_1. */
/* No need for trTi_Msg_PY_Tti_128_1. */
/* No need for trTi_Msg_DB_Tti_128_1. */
/* No need for trTi_Msg_CB_Tti_128_1. */
/* No need for trTi_Msg_CI_Tti_128_1. */
/* No need for trTi_Evt_PL_Tti_128_1. */
/* No need for trTi_Evt_DB_Tti_128_1. */
/* No need for trTi_Evt_CB_Tti_128_1. */
/* No need for trTi_Evt_CI_Tti_128_1. */
uint64_t trTi_Task_SB_Tti_128_1[128]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_Tti_128_1;
void trTask_Tti(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_Tti_128_1 =
{
	&trTi_Task_CB_Tti_128_1, /* ci_cb_p */ 
	trTask_Tti, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_Tti_128_1[0], /* ci_sb_p */ 
	1024, /* ci_StackSize */ 
	128 /* ci_NominalPriority */ 
};
const uint16_t trTi_NumOfTasks = 7;
const uint16_t trTi_NumOfTasks_PlusOne = 8;
const struct trTi_T_IB_s trTi_TaskInfoList[7] = /* This is sized trTi_NumOfTasks. */
{
	{
		&trTi_Task_CI_Tei_64_0, /* ib_t_p */
		NULL, /* ib_evt_p Tei has no Evt. */
		NULL, /* ib_msg_p Tei has no Msg. */
		NULL /* ib_strm_p Tei has no Strm. */
	},
	{
		&trTi_Task_CI_Tti_128_1, /* ib_t_p */
		NULL, /* ib_evt_p Tti has no Evt. */
		NULL, /* ib_msg_p Tti has no Msg. */
		NULL /* ib_strm_p Tti has no Strm. */
	},
	{
		&trTi_Task_CI_trTst01_action_256_2, /* ib_t_p */
		NULL, /* ib_evt_p trTst01_action has no Evt. */
		NULL, /* ib_msg_p trTst01_action has no Msg. */
		NULL /* ib_strm_p trTst01_action has no Strm. */
	},
	{
		&trTi_Task_CI_Tst01AAAA_43690_3, /* ib_t_p */
		NULL, /* ib_evt_p Tst01AAAA has no Evt. */
		NULL, /* ib_msg_p Tst01AAAA has no Msg. */
		NULL /* ib_strm_p Tst01AAAA has no Strm. */
	},
	{
		&trTi_Task_CI_Tst01CCCC_52428_4, /* ib_t_p */
		NULL, /* ib_evt_p Tst01CCCC has no Evt. */
		NULL, /* ib_msg_p Tst01CCCC has no Msg. */
		NULL /* ib_strm_p Tst01CCCC has no Strm. */
	},
	{
		&trTi_Task_CI_trTst01_init_255_5, /* ib_t_p */
		NULL, /* ib_evt_p trTst01_init has no Evt. */
		NULL, /* ib_msg_p trTst01_init has no Msg. */
		NULL /* ib_strm_p trTst01_init has no Strm. */
	},
	{
		&trTi_Task_CI_Tst01BBBB_48059_6, /* ib_t_p */
		NULL, /* ib_evt_p Tst01BBBB has no Evt. */
		NULL, /* ib_msg_p Tst01BBBB has no Msg. */
		&trTi_Strm_CI_Tst01BBBB_48059_6 /* ib_strm_p */
	}
};
const struct trBidt_Node_const_s trTi_TaskIDTree[8] = /* This is sized trTi_NumOfTasks_PlusOne. */
{
	{
		64, /* the_ID for Tei with idx 0 */
		65535, /* child_left is End */
		1  /* child_right is Tti at this idx. */
	},
	{
		128, /* the_ID for Tti with idx 1 */
		65535, /* child_left is End */
		65535 /* child_right is End */
	},
	{
		256, /* the_ID for trTst01_action with idx 2 */
		5, /* child_left is trTst01_init at this idx. */
		3  /* child_right is Tst01AAAA at this idx. */
	},
	{
		43690, /* the_ID for Tst01AAAA with idx 3 */
		65535, /* child_left is End */
		4  /* child_right is Tst01CCCC at this idx. */
	},
	{
		52428, /* the_ID for Tst01CCCC with idx 4 */
		6, /* child_left is Tst01BBBB at this idx. */
		65535 /* child_right is End */
	},
	{
		255, /* the_ID for trTst01_init with idx 5 */
		65535, /* child_left is End */
		65535 /* child_right is End */
	},
	{
		48059, /* the_ID for Tst01BBBB with idx 6 */
		65535, /* child_left is End */
		65535 /* child_right is End */
	},
	{
		0, /* the_ID for Root with idx 7 */
		0, /* child_left is Tei at this idx. */
		2  /* child_right is trTst01_action at this idx. */
	}
};
struct trPl_Lst_s trTi_TaskReadyResrc_pe[7];  /* This is sized trTi_NumOfTasks. */
struct trPl_Lst_s trTi_TaskTimeout_pe[7];  /* This is sized trTi_NumOfTasks. */
const uint16_t trTi_Tti_ID = 128;
const uint16_t trTi_Tti_idx = 1;
const uint16_t trTi_Tei_ID = 64;
const uint16_t trTi_Tei_idx = 0;
