/** \file
*   \brief ThingRendevous's Task Info implementation 
*
* Generated by Trtgen.py.
*/
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "trBidt.h"
#include "trPl.h"
#include "trEvt.h"
#include "trMsg.h"
#include "trStrm.h"
#include "trT.h"
#include "trEvtP.h"
#include "trMsgP.h"
#include "trStrmP.h"
#include "trTP.h"
#include "trTi.h"
/* No need for trTi_Strm_DB_Tti_128_1. */
/* No need for trTi_Strm_CB_Tti_128_1. */
/* No need for trTi_Strm_CI_Tti_128_1. */
/* No need for trTi_Msg_PL_Tti_128_1. */
/* No need for trTi_Msg_PY_Tti_128_1. */
/* No need for trTi_Msg_DB_Tti_128_1. */
/* No need for trTi_Msg_CB_Tti_128_1. */
/* No need for trTi_Msg_CI_Tti_128_1. */
/* No need for trTi_Evt_PL_Tti_128_1. */
/* No need for trTi_Evt_DB_Tti_128_1. */
/* No need for trTi_Evt_CB_Tti_128_1. */
/* No need for trTi_Evt_CI_Tti_128_1. */
uint64_t trTi_Task_SB_Tti_128_1[128]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_Tti_128_1;
void trTask_Tti(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_Tti_128_1 =
{
	&trTi_Task_CB_Tti_128_1, /* ci_cb_p */ 
	trTask_Tti, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_Tti_128_1[0], /* ci_sb_p */ 
	1024, /* ci_StackSize */ 
	128 /* ci_NominalPriority */ 
};
/* No need for trTi_Strm_DB_Tst06_workerBenton_520_5. */
/* No need for trTi_Strm_CB_Tst06_workerBenton_520_5. */
/* No need for trTi_Strm_CI_Tst06_workerBenton_520_5. */
/* No need for trTi_Msg_PL_Tst06_workerBenton_520_5. */
/* No need for trTi_Msg_PY_Tst06_workerBenton_520_5. */
/* No need for trTi_Msg_DB_Tst06_workerBenton_520_5. */
/* No need for trTi_Msg_CB_Tst06_workerBenton_520_5. */
/* No need for trTi_Msg_CI_Tst06_workerBenton_520_5. */
struct trPl_Lst_s trTi_Evt_PL_Tst06_workerBenton_520_5[5];
struct trEvtP_DB_s trTi_Evt_DB_Tst06_workerBenton_520_5[5];
struct trEvtP_CB_s trTi_Evt_CB_Tst06_workerBenton_520_5;
const struct trEvtP_CI_s trTi_Evt_CI_Tst06_workerBenton_520_5 =
{
	5, /* ci_EvtLen */ 
	&trTi_Evt_CB_Tst06_workerBenton_520_5, /* ci_cb_p */ 
	&trTi_Evt_DB_Tst06_workerBenton_520_5[0],  /* ci_db_p */ 
	&trTi_Evt_PL_Tst06_workerBenton_520_5[0]  /* ci_pl_p */ 
};
uint64_t trTi_Task_SB_Tst06_workerBenton_520_5[128]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_Tst06_workerBenton_520_5;
void trTask_Tst06_workerBenton(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_Tst06_workerBenton_520_5 =
{
	&trTi_Task_CB_Tst06_workerBenton_520_5, /* ci_cb_p */ 
	trTask_Tst06_workerBenton, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_Tst06_workerBenton_520_5[0], /* ci_sb_p */ 
	1024, /* ci_StackSize */ 
	32767 /* ci_NominalPriority */ 
};
/* No need for trTi_Strm_DB_Tst06_init_255_2. */
/* No need for trTi_Strm_CB_Tst06_init_255_2. */
/* No need for trTi_Strm_CI_Tst06_init_255_2. */
/* No need for trTi_Msg_PL_Tst06_init_255_2. */
/* No need for trTi_Msg_PY_Tst06_init_255_2. */
/* No need for trTi_Msg_DB_Tst06_init_255_2. */
/* No need for trTi_Msg_CB_Tst06_init_255_2. */
/* No need for trTi_Msg_CI_Tst06_init_255_2. */
/* No need for trTi_Evt_PL_Tst06_init_255_2. */
/* No need for trTi_Evt_DB_Tst06_init_255_2. */
/* No need for trTi_Evt_CB_Tst06_init_255_2. */
/* No need for trTi_Evt_CI_Tst06_init_255_2. */
uint64_t trTi_Task_SB_Tst06_init_255_2[128]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_Tst06_init_255_2;
void trTask_Tst06_init(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_Tst06_init_255_2 =
{
	&trTi_Task_CB_Tst06_init_255_2, /* ci_cb_p */ 
	trTask_Tst06_init, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_Tst06_init_255_2[0], /* ci_sb_p */ 
	1024, /* ci_StackSize */ 
	255 /* ci_NominalPriority */ 
};
/* No need for trTi_Strm_DB_Tei_64_0. */
/* No need for trTi_Strm_CB_Tei_64_0. */
/* No need for trTi_Strm_CI_Tei_64_0. */
/* No need for trTi_Msg_PL_Tei_64_0. */
/* No need for trTi_Msg_PY_Tei_64_0. */
/* No need for trTi_Msg_DB_Tei_64_0. */
/* No need for trTi_Msg_CB_Tei_64_0. */
/* No need for trTi_Msg_CI_Tei_64_0. */
/* No need for trTi_Evt_PL_Tei_64_0. */
/* No need for trTi_Evt_DB_Tei_64_0. */
/* No need for trTi_Evt_CB_Tei_64_0. */
/* No need for trTi_Evt_CI_Tei_64_0. */
uint64_t trTi_Task_SB_Tei_64_0[1]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_Tei_64_0;
void trTask_Tei(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_Tei_64_0 =
{
	&trTi_Task_CB_Tei_64_0, /* ci_cb_p */ 
	trTask_Tei, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_Tei_64_0[0], /* ci_sb_p */ 
	8, /* ci_StackSize */ 
	64 /* ci_NominalPriority */ 
};
/* No need for trTi_Strm_DB_Tst06_workerRace_530_3. */
/* No need for trTi_Strm_CB_Tst06_workerRace_530_3. */
/* No need for trTi_Strm_CI_Tst06_workerRace_530_3. */
/* No need for trTi_Msg_PL_Tst06_workerRace_530_3. */
/* No need for trTi_Msg_PY_Tst06_workerRace_530_3. */
/* No need for trTi_Msg_DB_Tst06_workerRace_530_3. */
/* No need for trTi_Msg_CB_Tst06_workerRace_530_3. */
/* No need for trTi_Msg_CI_Tst06_workerRace_530_3. */
struct trPl_Lst_s trTi_Evt_PL_Tst06_workerRace_530_3[5];
struct trEvtP_DB_s trTi_Evt_DB_Tst06_workerRace_530_3[5];
struct trEvtP_CB_s trTi_Evt_CB_Tst06_workerRace_530_3;
const struct trEvtP_CI_s trTi_Evt_CI_Tst06_workerRace_530_3 =
{
	5, /* ci_EvtLen */ 
	&trTi_Evt_CB_Tst06_workerRace_530_3, /* ci_cb_p */ 
	&trTi_Evt_DB_Tst06_workerRace_530_3[0],  /* ci_db_p */ 
	&trTi_Evt_PL_Tst06_workerRace_530_3[0]  /* ci_pl_p */ 
};
uint64_t trTi_Task_SB_Tst06_workerRace_530_3[128]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_Tst06_workerRace_530_3;
void trTask_Tst06_workerRace(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_Tst06_workerRace_530_3 =
{
	&trTi_Task_CB_Tst06_workerRace_530_3, /* ci_cb_p */ 
	trTask_Tst06_workerRace, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_Tst06_workerRace_530_3[0], /* ci_sb_p */ 
	1024, /* ci_StackSize */ 
	32767 /* ci_NominalPriority */ 
};
/* No need for trTi_Strm_DB_Tst06_idle_599_4. */
/* No need for trTi_Strm_CB_Tst06_idle_599_4. */
/* No need for trTi_Strm_CI_Tst06_idle_599_4. */
/* No need for trTi_Msg_PL_Tst06_idle_599_4. */
/* No need for trTi_Msg_PY_Tst06_idle_599_4. */
/* No need for trTi_Msg_DB_Tst06_idle_599_4. */
/* No need for trTi_Msg_CB_Tst06_idle_599_4. */
/* No need for trTi_Msg_CI_Tst06_idle_599_4. */
/* No need for trTi_Evt_PL_Tst06_idle_599_4. */
/* No need for trTi_Evt_DB_Tst06_idle_599_4. */
/* No need for trTi_Evt_CB_Tst06_idle_599_4. */
/* No need for trTi_Evt_CI_Tst06_idle_599_4. */
uint64_t trTi_Task_SB_Tst06_idle_599_4[128]; /* uint64_t forces each 8 byte element on an 8 byte boundary */
struct trTP_CB_s trTi_Task_CB_Tst06_idle_599_4;
void trTask_Tst06_idle(void *theTaskData);
const struct trTP_CI_s trTi_Task_CI_Tst06_idle_599_4 =
{
	&trTi_Task_CB_Tst06_idle_599_4, /* ci_cb_p */ 
	trTask_Tst06_idle, /* ci_someTask */ 
	NULL, /* ci_theTaskData_p */ 
	(uint8_t *) &trTi_Task_SB_Tst06_idle_599_4[0], /* ci_sb_p */ 
	1024, /* ci_StackSize */ 
	50000 /* ci_NominalPriority */ 
};
const uint16_t trTi_NumOfTasks = 6;
const uint16_t trTi_NumOfTasks_PlusOne = 7;
const struct trTi_T_IB_s trTi_TaskInfoList[6] = /* This is sized trTi_NumOfTasks. */
{
	{
		&trTi_Task_CI_Tei_64_0, /* ib_t_p */
		NULL, /* ib_evt_p Tei has no Evt. */
		NULL, /* ib_msg_p Tei has no Msg. */
		NULL /* ib_strm_p Tei has no Strm. */
	},
	{
		&trTi_Task_CI_Tti_128_1, /* ib_t_p */
		NULL, /* ib_evt_p Tti has no Evt. */
		NULL, /* ib_msg_p Tti has no Msg. */
		NULL /* ib_strm_p Tti has no Strm. */
	},
	{
		&trTi_Task_CI_Tst06_init_255_2, /* ib_t_p */
		NULL, /* ib_evt_p Tst06_init has no Evt. */
		NULL, /* ib_msg_p Tst06_init has no Msg. */
		NULL /* ib_strm_p Tst06_init has no Strm. */
	},
	{
		&trTi_Task_CI_Tst06_workerRace_530_3, /* ib_t_p */
		&trTi_Evt_CI_Tst06_workerRace_530_3, /* ib_evt_p */
		NULL, /* ib_msg_p Tst06_workerRace has no Msg. */
		NULL /* ib_strm_p Tst06_workerRace has no Strm. */
	},
	{
		&trTi_Task_CI_Tst06_idle_599_4, /* ib_t_p */
		NULL, /* ib_evt_p Tst06_idle has no Evt. */
		NULL, /* ib_msg_p Tst06_idle has no Msg. */
		NULL /* ib_strm_p Tst06_idle has no Strm. */
	},
	{
		&trTi_Task_CI_Tst06_workerBenton_520_5, /* ib_t_p */
		&trTi_Evt_CI_Tst06_workerBenton_520_5, /* ib_evt_p */
		NULL, /* ib_msg_p Tst06_workerBenton has no Msg. */
		NULL /* ib_strm_p Tst06_workerBenton has no Strm. */
	}
};
const struct trBidt_Node_const_s trTi_TaskIDTree[7] = /* This is sized trTi_NumOfTasks_PlusOne. */
{
	{
		64, /* the_ID for Tei with idx 0 */
		65535, /* child_left is End */
		1  /* child_right is Tti at this idx. */
	},
	{
		128, /* the_ID for Tti with idx 1 */
		65535, /* child_left is End */
		65535 /* child_right is End */
	},
	{
		255, /* the_ID for Tst06_init with idx 2 */
		65535, /* child_left is End */
		3  /* child_right is Tst06_workerRace at this idx. */
	},
	{
		530, /* the_ID for Tst06_workerRace with idx 3 */
		5, /* child_left is Tst06_workerBenton at this idx. */
		4  /* child_right is Tst06_idle at this idx. */
	},
	{
		599, /* the_ID for Tst06_idle with idx 4 */
		65535, /* child_left is End */
		65535 /* child_right is End */
	},
	{
		520, /* the_ID for Tst06_workerBenton with idx 5 */
		65535, /* child_left is End */
		65535 /* child_right is End */
	},
	{
		0, /* the_ID for Root with idx 6 */
		0, /* child_left is Tei at this idx. */
		2  /* child_right is Tst06_init at this idx. */
	}
};
struct trPl_Lst_s trTi_TaskReadyResrc_pe[6];  /* This is sized trTi_NumOfTasks. */
struct trPl_Lst_s trTi_TaskTimeout_pe[6];  /* This is sized trTi_NumOfTasks. */
const uint16_t trTi_Tti_ID = 128;
const uint16_t trTi_Tti_idx = 1;
const uint16_t trTi_Tei_ID = 64;
const uint16_t trTi_Tei_idx = 0;
